[애플 스토어 레이아웃 클론코딩] 주모(한준모) 미션 제출합니다.
woowacourse/html-apple-store pull request #15
Opened 2021-09-16 00:59 UTC by jum0

## 📝 PR 올리기 전 체크해봤나요?
- [ ] 불필요한 마크업은 없는가?
- [ ] 웹표준에 어긋나는 마크업은 없는가?
- [ ] css를 없앴을 때 실제 apple 웹사이트와 구조가 동일한가?
- [x] 모바일 화면에 맞게 반응형을 지원하는가?

## ✅ 마크업을 잘하기 위한 셀프 체크리스트
- [ ] LightHouse 측정결과에서 웹 접근성 항목에 빨간색(?) 요소가 없는가.
- [x] break point 고려하기
- [ ] css 코드 복잡도 측정하기

## 느낀점
- css로 짜본 게 얼마만인지 모르겠는데.. 쉽지 않다ㅠ 그냥 styled component로만 하고 싶네요ㅠㅜ
- 웹 표준에 맞게 시멘틱 태그를 사용하려고 시도 하지도 못한 듯 하다. 아무래도 특정 해상도에 따른 크기가 정해져 있다보니, 그거랑 똑같이 만들려고 하는데 더 집중했던 것 같다. 이번 미션에서 원하는 건 그게 아닌 걸 알면서도 목적에 부합하지 못했던 것 같다.

2021-09-17 02:34 UTC, 0imbean0 requested changes
안녕하세요 주모. 심밤니다. 🦁
우선 어제 리뷰 못드려서 죄송합니다. 🙏

미션을 진행하면서 의문이 생겼던 부분에 대해 의견을 들어보고자 코멘트 남겼어요.

수고하셨습니다.

2021-09-17 02:34 UTC, 0imbean0 commented on index.html
> +      </section>
`hero`와 달리 `<div class="iphone-13-pro-picture"></div>` 를 따로 만드는 이유가 뭘까요? 🤔
(애플 사이트에 이렇게 되어있어서 저도 이렇게 했는데, 주모의 의견이 궁금해서 질문 드렸어요. )

2021-09-17 02:34 UTC, 0imbean0 commented on src/css/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
이게 방금 준이 말씀하신 `normalize.css` 군요 👍

2021-09-26 04:25 UTC, jum0 commented on index.html
> +      </section>
질문해주신 부분이 `hero와 다르게 iphone-13-pro는 왜 여러 컨테이너들이 있는지?`가 맞나요?

이미지의 세부적인 위치 조정을 위해서 이렇게 만들었어요! `hero`는 화면 크기에 따라서 이미지만 달라질 뿐 이미지가 보여지는 위치는 변경되지 않지만, `iphone-13-pro`는 화면 크기에 이미지가 보여지는 컨테이너 자체가 오른쪽에 있다거나, 아래로 내려가는 등 달라지더라구요. 그래서 세부적으로 조정하다가보니 둘러싸는 여러 컨테이너가 필요했습니다!

2021-09-27 08:28 UTC, 0imbean0 commented on index.html
> +      </section>
아 맞네용. 
`hero` 처럼 그냥 배경까지 넣은 이미지로 만들면 편했을거 같은데, 왜 이미지를 이리 저리 움직이는 건지. 
(우리가 클론하는걸 알고 난이도 올리려고? 🤔)

2021-09-27 08:29 UTC, 0imbean0 approved these changes
수고하셨습니다. 주모.
내일 수업에서 봐요.

2021-09-27 08:29 UTC, merged