[애플 스토어 레이아웃 클론코딩] 서니(박선희) 미션 제출합니다.
woowacourse/html-apple-store pull request #21
Opened 2021-09-16 01:27 UTC by sunhpark42

## 📝 PR 올리기 전 체크해봤나요?
- [x] 불필요한 마크업은 없는가?
- [x] 웹표준에 어긋나는 마크업은 없는가?
- [x] css를 없앴을 때 실제 apple 웹사이트와 구조가 동일한가?
  - image 태그 를 제외한 구조 동일
- [x] 모바일 화면에 맞게 반응형을 지원하는가?

## ✅ 마크업을 잘하기 위한 셀프 체크리스트
- [x] 시맨틱 태그를 적절히 사용하였는가
- [ ] 불필요하거나 의미 없는 요소를 쓰지 않고 중복이 적은가
- [ ] 스크린 리더로 내용을 이해하는데 문제가 없는가
- [x] Lighthouse 웹 접근성 점수가 95점 이상인가
<img width="1215" alt="스크린샷 2021-09-16 오전 10 23 40" src="https://user-images.githubusercontent.com/67677561/133534322-9c7731bc-991c-4fa1-b057-1515eda0b296.png">
- [ ] 반응형을 고려한 레이아웃을 구현하였는가
  - footer 제작 x
<img width="508" alt="스크린샷 2021-09-16 오전 10 17 25" src="https://user-images.githubusercontent.com/67677561/133534386-ca658526-7879-41a7-8af9-d4761b1fb320.png">
<img width="895" alt="스크린샷 2021-09-16 오전 10 15 37" src="https://user-images.githubusercontent.com/67677561/133534397-3bc1c172-df61-4789-b982-f87fd92e8493.png">
<img width="1292" alt="스크린샷 2021-09-16 오전 10 14 42" src="https://user-images.githubusercontent.com/67677561/133534412-5af3afbc-e150-495e-8c2b-2658d6feb9f2.png">
<img width="486" alt="스크린샷 2021-09-16 오전 10 15 14" src="https://user-images.githubusercontent.com/67677561/133534442-fee473d9-fe78-48e9-9b30-8fa691fa3f15.png">
- [x] 여러 브라우저(크롬, 사파리, 엣지, 파이어폭스)에서 봤을 때에도 모두 같은 화면을 보여주는가
  - 크롬, 사파리만 확인
- [x] CSS를 제거해도 마크업 구조가 유지되는가

미완성이라서, 우선 미션 먼저 제출합니다~ 리뷰 잘 부탁드려요!

2021-09-16 15:22 UTC, dudtjr913 requested changes
서니! 역시 잘하는군요. 클래스명이 한 눈에 들어와서 읽기가 편했습니다! 시멘틱태그도 잘 사용해주셨고, shared라는 폴더에 공통적으로 사용되는 스타일을 모아놓은 것도 좋았습니다!! 시간이 부족했음에도 어느 정도 반응형이 모두 완성된 것 같은데 대단해요.👍👍👍👍

수직 정렬이 되지 않은 부분이 있어요! 이 부분을 고친다면 짱!👍
![image](https://user-images.githubusercontent.com/64782636/133638016-804dcbde-1d8f-4dcb-a6a7-685df8facca0.png)

아쉽게도 시간이 부족해서 footer와 화면이 좁아졌을 때 처리가 안된 것 같은데, 간단하게만 구현해보는 것도 좋을 것 같아요! (꼭 안하셔두 됩니닷😍)

`추가적으로 여러 브라우저(크롬, 사파리, 엣지, 파이어폭스)에서 봤을 때에도 모두 같은 화면을 보여주는가`에 대해서 엣지와 ie에서도 테스트를 해봤는데 엣지는 정상 동작하고, ie는 몇몇 레이아웃이 깨지고 있어요! 하지만 ie라서... 이 부분도 서니의 결정에 맡기겠습니다!

많은 인사이트를 드리지 못한 것 같아서 죄송하네요..😭 수고하셨습니다~

2021-09-16 15:22 UTC, dudtjr913 commented on index.html
> +  <link rel="stylesheet" href="./src/css/font.css" type="text/css" media="all" />
여기에 media="all"이 있는 이유가 무엇일까요??

2021-09-16 15:22 UTC, dudtjr913 commented on index.html
> +  <h1 id="site-header" class="visibility-hidden">Apple</h1>
오오 대박 접근성 고려!!

2021-09-16 15:22 UTC, dudtjr913 commented on index.html
> +  <nav id="global-nav" role="navigation" aria-label="Global" lang="en-US">
lang도 있군요. 새로운 정보 줍줍

2021-09-16 15:22 UTC, dudtjr913 commented on index.html
> +          <label>
🙋‍♀️ label이 있는 이유가 무엇인가요?

2021-09-16 15:22 UTC, dudtjr913 commented on src/css/@shared/layout.css
> +}
자주 사용되는 속성들을 모아서 관리하는 것이 굉장히 좋아보여요!

2021-09-16 15:22 UTC, dudtjr913 commented on src/css/index.css
> +  background-color: #000;
호버까지 모두 적용하셨군요.👍👍

2021-09-16 15:22 UTC, dudtjr913 commented on src/css/index.css
> +  color: #f5f5f7;
이번에 저도 알게되었는데, 자주 사용되는 컬러는 css 변수로 관리하면 좋을 것 같아요😍https://developer.mozilla.org/ko/docs/Web/CSS/Using_CSS_custom_properties

2021-09-16 15:22 UTC, dudtjr913 commented on src/css/index.css
> +  min-height: 83px;
min-height와 height를 같이 준 이유가 있나용?

2021-09-16 15:22 UTC, dudtjr913 commented on src/css/index.css
> +  display: flex;
위쪽에 display:block은 삭제해도 될 것 같네요!

2021-09-16 15:22 UTC, dudtjr913 commented on src/css/index.css
> +  z-index: 3;
이 프로젝트에서는 필요하지 않고, 서니도 알 것 같지만 z-index도 따로 관리하면 좋다고하네요!

2021-09-17 02:28 UTC, sunhpark42 commented on index.html
> +          <label>
해당 ul 을 대표하는 label(제목)이라고 생각해서 라벨을 사용했습니다~

2021-09-17 02:29 UTC, sunhpark42 commented on src/css/index.css
> +  color: #f5f5f7;
오..css 변수도 사용이 가능하네요 대박.. 역시 디토

2021-09-17 02:29 UTC, sunhpark42 commented on src/css/index.css
> +  z-index: 3;
실제 프로젝트에선 따로 관리하고 있는데, 이 프로젝트에서는 분리할 시간이 따로 없었습니다. 😂😂 반영할 시간 있으니 반영하겠습니다~

2021-09-17 02:31 UTC, sunhpark42 commented
nav.. 수직정렬 했다고 생각했는데, 브라우저별로 좀 다르게 보이나보네요. 윈도우 환경의 브라우저에서 확인이 어렵다는게 슬픕니다.. 광광..

ie는 제외하고 레이아웃을 구성해서, 그 부분은 감안해주시면 감사하겠습니다! 시간상 못건드린 부분이 있었는데, 토요일 중으로 반영해서 다시 리뷰 부탁드리겠습니다. 리뷰 감사합니다👍👍

2021-09-28 14:03 UTC, sunhpark42 commented
조금..많이...늦었습니다... 죄송해요 디토 😂 푸터는 이번에 못할 것 같아서 제외하였습니다. 감사합니다~

2021-09-28 14:30 UTC, dudtjr913 approved these changes
고생하셨어용~ 접근성 미션도 화이팅!!

2021-09-28 14:31 UTC, merged