[애플스토어 레이아웃 클론코딩] 신세한탄(신세희) 미션 제출합니다.
woowacourse/html-apple-store pull request #24
Opened 2021-09-16 04:09 UTC by shinsehantan

## 📝 PR 올리기 전 체크해봤나요?
- [ ] 불필요한 마크업은 없는가?
- [x] 웹표준에 어긋나는 마크업은 없는가?
- [ ] css를 없앴을 때 실제 apple 웹사이트와 구조가 동일한가?
- [ ] 모바일 화면에 맞게 반응형을 지원하는가?

## ✅ 마크업을 잘하기 위한 셀프 체크리스트
- [x] 태그만으로 레이아웃 구조가 눈에 그려지는가
- [ ] 반응형을 고려하였는가

[## 데모페이지](https://shinsehantan.github.io/html-apple-store/index.html) 

안녕하세요 리뷰어님ㅠ 10시까지인 줄 몰라서 제출을 가장 늦게 하네요ㅠㅠ
어제 밤을 샜지만...... 정말 제출하기 민망한 수준입니다.... 
푸터는 반응형도 시도하지 못했네요ㅠㅠ
완성된 부분을 봐주시면 감사하겠습니다....
데모를 보니 갑자기 히어로 이미지가 뜨질 않는데... 이유는 찾아보도록 하겠습니다 ㅠ

2021-09-18 15:33 UTC, ddongule requested changes
안뇽하세요 신세한탄! 그루밍입니다! >_ㅇㅎㅎㅎ
먼저 어제는 데모 끝나고 기절했고.. 
오늘은 좀 뜅굴뜅굴 하다가 리뷰가 늦었네요.. 죄송합니다 뀩ㅜㅜ
신세한탄도 발표 준비하랴 미션하랴 여러모로 엄청 빡센 한 주였을 것 같습니다..🥲 
미션하느라 고생하셨어요!

코드를 보면서 궁금했던 점들을 몇가지 리뷰 남겨놨어요!
한 번 보시고 적용하실 부분이 있다면 적용하시고 필요 없다고 느끼시는 부분에 대해서는 적용 안하셔도 좋습니다아~~!! >_ㅇㅎㅎㅎ
그리고 반응형 부분에서 Desktop → Mobile 넘어갈 때에 메인 타이틀 부분이 좌측 정렬되는 문제가 조금 있는 것 같아요! 한 번 확인해주시면 좋을 것 같습니다!!!!!!! 

수고하셨어요 신세한탄~~!!!!! 추석 즐겁게 보내십시요 ㅎㅎㅎㅎ 💛😘🧡💛😘🧡

2021-09-18 15:33 UTC, ddongule commented on src/css/reset.css
> +i,
`reset.css`를 가져와서 사용하신 것 같은데, 사용하지 않는 부분이 많은 것 같아요!
사용하시는 부분만 가져와서 사용하시면 어떨까요~?

2021-09-18 15:33 UTC, ddongule commented on src/images/bag.svg
> +</svg>
`images` 폴더에 이미지랑 `svg`가 섞여있네요!
폴더를 나누어보는 것은 어떤가요? 🤔

2021-09-18 15:33 UTC, ddongule commented on index.html
> +            <div class="line-divider"></div>
`border-bottom`이나 `border-top`을 사용하지 않고 div로 line을 그려주신 이유가 있으실까욤?

2021-09-18 15:33 UTC, ddongule commented on index.css
> +}
hidden만 여기에 위치한 이유가 있을까요~? 공통으로 쓰이는 친구라면 공통 파일을 만들어서 넣는 것도 좋아보여요!

2021-09-18 15:33 UTC, ddongule commented on index.html
> +            <li class="nav-icon sm-nav-icon icon-bag"></li>
`<li class="nav-icon sm-nav-icon icon-apple"></li>`
`<li class="nav-icon sm-nav-icon icon-bag"></li>`
요 부분이 겹치는데, 겹치지 않게 하는 방법은 없을까요?

2021-09-18 15:33 UTC, ddongule commented on index.html
> +            </h3 class="hero-description-item">
`class`속성이 닫힘 태그에도 들어가있어요! 복사하다가 잘못 들어간 것 같군요 호홋 ㅎㅎ

2021-09-18 15:33 UTC, ddongule commented on index.html
> +              </span>
description에 `span` 태그를 사용하신 이유가 있으신가욤? 
개인적으로 제 생각에는 요 부분이 단순히 description이라기 보다는 약간 부제목 느낌이 강해서 
저는 heading 태그를 줬었거든요! 그냥 이유가 궁금해서 여쭤봅니당 헤헷

2021-09-18 15:33 UTC, ddongule commented on index.html
> +            <img class="iphone13pro-flex-image" src="./src/images/iphone_13_pro_small_2x.jpeg"/>
요 부분은 background image를 사용하지 않은 이유가 있으실까욧?!

2021-09-24 12:13 UTC, shinsehantan commented on src/css/reset.css
> +i,
별 생각없이 복붙해서 가져다 사용했는데 불필요한건 삭제하는 게 좋겠네요ㅎㅎㅎ 감사합니당!

2021-09-24 12:15 UTC, shinsehantan commented on src/images/bag.svg
> +</svg>
오.. 저는 사실 프로젝트에서도 svg 파일을 따로 나눠서 보관하질 않았는데 대부분 폴더를 따로 나누는 편인가요????

2021-09-24 12:23 UTC, shinsehantan commented on index.html
> +            <div class="line-divider"></div>
음... 딱히 이유는 없었습니당..! 종종 border를 사용하면 원하는대로 간격을 조정하기 어려울 때가 있었어서 이렇게 했던 것 같은데, 사실 여기서는 전혀 문제가 될 게 없기도 하고, 불필요한 div를 추가해서 사용하느니 border-bottom이 낫겠네요! 수정했습니다 ㅎㅎㅎ

2021-09-24 12:26 UTC, shinsehantan commented on index.css
> +}
원래 저 index.css에 global 성격을 지닌 애들을 쭉 놓을 계획이었는데, 대부분 main으로 들어가버려서... 저아이 혼자 낙동강 오리알마냥 남아있었네요..! index는 다른 폴더 import 구문만 놔두고 global.css로 옮겼습니다ㅎㅎㅎ

2021-09-24 12:28 UTC, shinsehantan commented on index.html
> +            </h3 class="hero-description-item">
어머나... 꼼꼼한 리뷰어님 감사합니다!!!

2021-09-24 12:30 UTC, shinsehantan commented on index.html
> +              </span>
사실 조금 고민했던 부분이었는데, 4문장이나 돼서 부제목 느낌으로 보기엔 다소 길다고 느껴져서 span 태그를 사용했습니다ㅎㅎㅎ

2021-09-24 12:50 UTC, shinsehantan commented on index.html
> +            <img class="iphone13pro-flex-image" src="./src/images/iphone_13_pro_small_2x.jpeg"/>
이 이미지는 위 메인 배너 부분과는 다르게 배경 이미지 성격이 아니라고 생각했었는데, background image를 사용하면 원하는만큼 오른쪽으로 옮겨서 crop 하는 것이 더 쉬웠을 것 같기도 하네요!

2021-09-24 12:54 UTC, shinsehantan commented
@ddongule 안뇽하세요 그루밍!! 리뷰 반영해보았는데, 확인해주시면 감사하겠습니당 ><

2021-09-24 14:11 UTC, ddongule commented on src/images/bag.svg
> +</svg>
아항! 저는 개인적으로 이미지랑 SVG가 같이 있는게 불편해서 나누어서 사용하는 편이라 한번 제안드려 봤어요!!!!
사용하시는 데 불편함이 없으시다면 굳이 나눌 필요는 없어보입니당! 헤헤헤 🙆🏻‍♀️

2021-09-24 14:15 UTC, ddongule commented on index.html
> +            <div class="line-divider"></div>
아아 맞아요 !!!!! !!!!! 
저같은 경우에도 border를 사용하게되면 의도치않게 border이 잡아먹는 픽셀때문에
간격 등을 조절하기 힘든 부분이 종종 생겼었던 기억이 나네요.. 😤 (극공감)
정답은 없지만 개인적으로는 그래도 의미없는 div 보다는 border를 조금 더 선호하게 되는 것 같아요 허헛 ㅎㅎ
왜 이 방법을 선택하셨나 궁금해서 남긴 리뷰였는데, 반영해주셔서 감사합니다 >_ㅇ ㅎㅎㅎ😘

2021-09-24 14:28 UTC, ddongule commented on index.html
> +            <li class="nav-icon sm-nav-icon icon-bag"></li>
요 부분은 건너뛰셨길래 한번 더 댓글을 달아봅니당! 
제가 말을 모호하게 써놔서 다시 보면서도 내가 뭔말을 한거지..? 싶었네요 ㅋㅋㅋㅋㅋ;ㅋ;;; 
우선 송구합니다 따호혹 ,, 😱

요 말을 조금 더 풀어서 설명하자면, 
지금 desktop version의 navigation과 mobile version의 navigation을 모두 만들어 사용하고 계시더라구요!
아래처럼요!

#### Desktop version
```html
  <ul class="nav-list">
    <li class="nav-icon icon-apple"></li>
    <li>Store</li>
    <li>Mac</li>
    <li>iPad</li>
    <li>iPhone</li>
    <li>Watch</li>
    <li>Music</li>
    <li>Support</li>
    <li class="nav-icon icon-search"></li>
    <li class="nav-icon icon-bag"></li>
  </ul>
```

#### mobile version
```html
  <ul class="sm-nav-list">
    <li class="nav-icon sm-nav-icon icon-menu"></li>
    <li class="nav-icon sm-nav-icon icon-apple"></li>
    <li class="nav-icon sm-nav-icon icon-bag"></li>
  </ul>
```

그런데 사실 아래의 mobile version의 코드는 desktop version의 navigation에도 있는 코드라서,
이 코드를 줄일 수 있는 방법을 한 번 생각해보시면 어떨까라는 생각이었습니다!

화면 크기가 줄어들면, 저 mobile version에서 사용되는 icon들을 제외하고 
나머지 친구들을 `display: none`을 통해 가려주는 방법도 있을 것 같아서, 한번 말씀드려봤습니당 >_ㅇ!!!! 

🍯 Hint!
css의 `:not()` 속성과 `:nth-child()` 속성을 한 번 사용해보세용 ㅎㅎ

2021-09-24 14:52 UTC, ddongule requested changes
안녕하세요 신세한탄!
리뷰 반영해주신 부분 잘 확인했습니다! 😘 
수고하셨어용 >_ㅇ!!ㅎㅎㅎㅎ

몇가지 덧붙인 부분이 있는데, 한 번 슥- 읽어봐주세요! 
수정하셔도 좋고, 안하셔도 좋습니다! 이미 잘 동작하는 코드라서요! 🙆‍♂️
읽고 알려주시면 approve 드리겠습니당 🧡

p.s) review로 남기지 않고 그냥 댓글로 남겼더니 나머지 댓글들이 위에 가있네요.... 
보시는데 불편드려서 죄송합니다 ㅜㅅ ㅜ 귀찮으시겠지만 위로 스크롤 올려서 댓글 한 번 확인해주세요호.. 
ㅜㅅ ㅜ🥺

2021-09-24 14:52 UTC, ddongule commented on index.html
> +              </span>
아항항 그렇군요! 궁금증 해결!!!! >_ㅇ!!!!!
그런데 살짝 더 오지랖.. 부려도 될까요..? (죄송합니다🥲) 그냥 읽고 넘어가주세유..!

지금은 마크업미션이라 크게 상관은 없을 듯 하지만..! 
그래도 나중에 접근성 측면에서 아무런 의미가 없는 [`span`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span) 태그를 사용하시는 것보다는 
문단의 의미를 가지는 `p` 태그, 혹은 description임을 나타낼 수 있는 다른 태그들을 사용해보셔도 좋을 것 같습니다!

그럼 총총,,

2021-09-24 14:52 UTC, ddongule commented on index.html
> +            <img class="iphone13pro-flex-image" src="./src/images/iphone_13_pro_small_2x.jpeg"/>
두 가지를 섞어서 사용하셔서, 궁금해서 여쭤본 거였습니당 >_ㅇ!! 
답변 감사합니다! 😘

2021-09-25 05:33 UTC, shinsehantan commented on index.html
> +            <li class="nav-icon sm-nav-icon icon-bag"></li>
ㄲ ㅑ 해냇더용

2021-09-25 05:33 UTC, shinsehantan commented
그루밍 선생님의 가르침으로 중복을 제거할 수 있었습니댜 꺄 제가 css 선택자에 진짜 약한데 덕분에 많이 배웠습니다>< 감사합니당!!!

2021-09-25 06:47 UTC, ddongule approved these changes
77ㅑ 수고하셨습니당 신세한탄!!!! 😘😘
넘넘 잘 반영해주셨꾼요 쵝오에욧!!! >_ㅇ💕
이제 하산하십쇼 ㅎ ㅣ ㅎ ㅣ
머지드리겠습니다 🥳🥳🥳🥳

2021-09-25 06:47 UTC, merged