[애플 스토어 레이아웃 클론코딩] 그루밍(강민경) 미션 제출합니다.
woowacourse/html-apple-store pull request #3
Opened 2021-09-15 19:22 UTC by ddongule

# [🌿 그루밍 데모 페이지](https://ddongule.github.io/html-apple-store/)

안뇽하세요 리뷰어님! 💫🍑
그루밍입니다 홍홍홍 이번 마크업 미션 잘부탁드립니다아~~!!!
저는 애플의 대대적인 발표가 있기 전 프로젝트를 시작해버려서 부득이하게도 그 이전 페이지에 대해 마크업을 진행했습니다...!!!!
그래서 지금 클론하던 홈페이지가 사라져버린 상태입니다. <<ㅏ흐흑!!!!! 😞🥲
다행히도 우테코의 복지 하루(@365kim)께서 노션에 캡쳐를 해주셔서 그 내용을 보고 만들었습니다! 😆😘
리뷰어님께서도 [요 링크](https://ubiquitous-radish-5e7.notion.site/61ef9002c9d747039160c6a7a6aa790d)에서 첨부된 사진을 보시고 리뷰하시면 좋을 것 같습니다. 불편하게 해드려서 송구하옵니다 ㅠㅅ ㅠ,, 
그럼 리뷰해주셔서 감사합니다아~~!!! 🧡💛🧡💛🧡
Special Thanks to 하루루루💙

## 📝 PR 올리기 전 체크해봤나요?
- [x] 불필요한 마크업은 없는가?
- [x] 웹표준에 어긋나는 마크업은 없는가?
- [x] css를 없앴을 때 실제 apple 웹사이트와 구조가 동일한가?
- [x] 모바일 화면에 맞게 반응형을 지원하는가?

## ✅ 마크업을 잘하기 위한 셀프 체크리스트
- [x] 디바이스와 브라우저에 관계없이 내가 목표한대로 유저에게 사이트가 보여지는가?
- [x] Lighthouse 접근성 영역이 95점 이상인가?
        <img width="832" alt="Screen Shot 2021-09-16 at 3 50 15 AM" src="https://user-images.githubusercontent.com/26598561/133492087-55d5e919-14ad-4660-b765-bd4eba535b71.png">
- [x] 순수 HTML만으로도 구조가 잘 잡혀 있는가?
- [x] 공통된 속성들을 활용해 코드의 반복이 최소한인가?
- [x] 시맨틱한 태그인가?

## 🐤 마크업 미션 후기
- 저는 개인적으로 마크업하는걸 좋아해서 재밌게 했습니다. 호호호 애플 사이트 언젠가 클론해보고 싶다는 생각을 했었는데 맨날 미루다가 이렇게 하게 되네요..! 이전 애플 사이트는 좀 더 인터랙티브 했던 것 같은데.. 그런 사이트였으면 더 재밌었을텐데.. (물론 재미만) ^^.. 어쨌든 재밌었습니다-! 포홍홍홍홍
- 그런데 미션을 조금 잘못 이해해서 아주 Raw하게 짜야하는 줄 알고 css 폴더도 안나누고 index.css에 모든 내용을 박아넣어버렸습니다..! 리뷰하시기 전에 얼른 나누고 다시 커밋해놓겠습니다..! 안해놓으면 혼내주세요..! ㅠㅠ 🥲🥲🥲
- hero video를 넣는 것이 아주 골아픈 일이었습니다..^^.. 어떻게든 해낸 것 같아서(?) 기쁩니다.
- 자바스크립트가 따로 필요한 곳이 없었어서 자바스크립트는 사용하지 않았습니다.
- `rem`, `px`를 섞어썼습니다... 리팩토링 할 때 하나의 단위로 맞추어 주는 편이 좋을 것 같다는 생각이 듭니다.ㅠㅠ!
- 자주 쓰이는 html, css들에서 최대한 반복을 줄이고 싶었는데 곳곳에서 보이는 것 같습니다.. 더 노력해보겠습니다앗

리뷰해주셔서 감사해용홍홍 🐰🧡 
뿌힝힝 >___ㅇ 오늘도 좋은 하루 행복한 하루 되시길 바래요
꺄루루 😘

2021-09-16 16:34 UTC, bucketHaneul requested changes
안녕하세요 그루밍! 엘라입니다 ㅎㅎ 루밍의 데모사이트를 보고 깜짝 놀랐어요,,,데모데이 준비때문에 바쁘셨을텐데 언제 다 이렇게 완벽하게 하셨죠,,? 정말로 존경합니다 🧚‍♀️🧚‍♀️🧚‍♀️ 정말 거의 apple 공홈과 싱크로울 99.999999%인것 같아요 ㅜㅜㅜ 추후에 css파일 분리하겠다고 하셨는데 이미 적용이 완료되어있더라구요 👍🏻👍🏻👍🏻

그루밍의 코드를 보면서 새로 알게된 부분이 있어서 오히려 저한테 더 인사이트있는 코드리뷰였습니당! 감사합니당 💙

그런데 코드를 보다보니 다음과 같은 질문이 생겼어요!
- `id`와 `class`중 어떤걸 사용할지 정하는 그루밍의 기준이 궁금해요!
- 이번 애플 공홈에서 어디부터 어디까지 footer로 생각하신건지도 궁금해요!!

앗 그리고 몇몇 svg 파일에 `No newline at end of file` 이 친구가 발견이 되었어요 🥲

사실 제가 뭐 따로 피드백 적용을 요청드릴 부분이 없었어요,,,(이미 완벽,,) 위 질문들에 대해 자유롭게 답변 달아주시고 코멘트 확인해주세요 ㅎ ㅎ 그러면 바로 머지하겠습니다! 정말 바빴을텐데 너무너무 고생하셨습니다! 

마크업을 좋아한다고 하셨는데 눈누난나 하면서 코딩하셨을 루밍이 뭔가 상상돼서 괜히 저도 신나네요ㅎㅎ

2021-09-16 16:34 UTC, bucketHaneul commented on index.html
> +    <main class="main">
여기서 왜 `class="main"`을 id가 아닌 class로 주셨는지 궁금해요 루밍!

저는 이번 미션을 하면서 언제 class를 쓸지 id를 쓸지에 대해 많이 고민한 것 같아요!! 그래서 한 곳에서 유니크하게 쓰이는 스타일인 경우에만 id를 주고 나머지는 class를 주자! 라고 결론을 내렸는데, 

혹시 루밍만의 언제 id를 사용하고 언제 class를 사용하는지에 대한 기준이 있으신가요?? 있다면 꼭 공유해주세요 😃

2021-09-16 16:34 UTC, bucketHaneul commented on index.html
> +          </div>
hoxy `cta`라는 단어는 무슨 뜻인가요?? 뭔가 여기저기서 많이봤던 단어인것 같은데 범용적으로 쓰이는 단어인가요?? 호기심에 한 번 여쭤봅니당 ㅎㅡㅎ

2021-09-16 16:34 UTC, HyuuunjuKim commented on index.html
> +            <a href="#" class="arrow-link">Buy</a>
오홍 이렇게 `class="arrow-link"`로 링크마다 화살표(>)를 넣으셨군요!!! 너무 좋은 아이디어인것 같아요!!!! 훨씬 유동적으로 링크 태그를 관리할 수 있겠네요!! 루밍 덕에 하나 배워갑니다 👍🏻👍🏻👍🏻

2021-09-16 16:34 UTC, HyuuunjuKim commented on index.html
> +            The first fitness service powered by Apple Watch. Try it for 1month free.<sup>2</sup>
`sup-element`라는게 있군요!!!!! 루밍 너무 꼼꼼하게 마크업 잘 하셨네요 ㅜㅜㅜㅜ 또 배워갑니다 💙

2021-09-16 16:34 UTC, HyuuunjuKim commented on index.html
> +      <section class="global-footer-contents">
왜 여기부터 `footer-element`로 감싸지 않고 406번째 줄부터 `footer-element`를 사용하신건지 궁금해요!!
`footer-element` 밖에 있는데 class명에 footer가 들어가니깐 조금 네이밍이 헷갈리는,,?느낌도 있는것 같네요! ㅎㅎ

2021-09-16 16:34 UTC, HyuuunjuKim commented on index.html
> +                <li><a href="#">Shopping Help</a></li>
푸터 nav 쪽 텍스트 넘 많지 않던가요 ㅜㅜㅜ 전 이거 하나씩 복붙하면서 지쳐버렸어요 ㅜ ㅜㅜㅜㅜㅋㅋㅋㅋㅋ쿠ㅜㅜㅜ쿠ㅜㅜ

2021-09-16 16:34 UTC, HyuuunjuKim commented on src/css/global.css
> +
이렇게 heading 태그를 관리하신게 되게 인상 깊네요!! 👍🏻👍🏻👍🏻

2021-09-16 16:34 UTC, HyuuunjuKim commented on src/svg/cart.svg
> +</svg>
호고곡 🥷🏻

2021-09-16 17:13 UTC, bigsaigon333 commented
그루밍 공홈 페이지를 데모 링크에 걸어두는 건 반칙입니다

2021-09-16 17:13 UTC, bigsaigon333 commented on index.html
> +            The first fitness service powered by Apple Watch. Try it for 1month free.<sup>2</sup>
what is sup??

2021-09-16 17:14 UTC, bigsaigon333 commented on index.html
> +          </div>
cta means call-to-action

2021-09-18 15:49 UTC, ddongule commented on index.html
> +    <main class="main">
오옹 저도 한 곳에만 유니크한 스타일을 할 때 id 속성을 사용하는데요!!!! 🙆‍♂️ 🙆‍♂️ 
최근들어 거의 react만 사용하다보니 id 값을 거의 JS에서 제어하기위한 용도로만 사용하다보니.. 
이번 미션에서 id를 사용하지 않았네요 🤔 ㅋㅋㅋㅋㅋㅋㅋ하핫핫!!!!!

아마.. 이건 그냥 제 취향인데 제가 마크업 할 때 class를 주로 사용하는 것 같아욤. 뭔가 재사용의 가능성을 열어두는 느낌?
아임 오픈 마인디드 .

2021-09-18 15:49 UTC, ddongule commented on index.html
> +          </div>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 오 저도 이번에 알게된 단어입니다,, 애플 사이트 슥 보니까 있어서 저도 썼어요 ^^ ,, ,,  ㅎ,, 머쓱,,
동동 답변 고마워요오후~ ㅎㅎㅎㅎㅎ>_ㅇ 💛

2021-09-18 15:49 UTC, ddongule commented on index.html
> +            <a href="#" class="arrow-link">Buy</a>
사랑해요 . ❤️

2021-09-18 15:51 UTC, ddongule commented on index.html
> +            The first fitness service powered by Apple Watch. Try it for 1month free.<sup>2</sup>
yo wassup~~~~~ 😎
sup은 요론 친구에요. [링크](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup)
사실 저도 이번에 마크업 미션 하면서 찾아봤다능.  . .   .  어려운 마크업의 세계, , , ,  , >_ㅇ 😘

2021-09-18 15:57 UTC, ddongule commented on index.html
> +      <section class="global-footer-contents">
아항 이게 제가 마크업 raw하게 먼저 하고 나중에 class 붙인거라서 .. 막 세심하게 신경쓰지 못한 부분이군요 하흐하핳 ㅋㅋㅋㅋㅋ 북끄 🥺
흠 제 생각에 푸터가 두 영역으로 나누어지는 것 같은데 .. 제가 <footer>로 감싼 부분은 어느 페이지에나 들어가는 부분인 것 같고, <section>으로 감싼 footer는 어떤 페이지에는 들어가지 않는 부분인 것 같아서 페이지 영역에 속한 느낌이 강한 것 같다고 느껴서 요렇게 영역을 나눠봤어욥! 
근데 사이트 들어가보니까 여기부터 다 푸터로 쓰이네요 .ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저런.. 
고쳐보겠숩니다!!!!!

2021-09-18 15:58 UTC, ddongule commented on index.html
> +                <li><a href="#">Shopping Help</a></li>
아이거참 공감합니다 ㅠ ㅠ ㅠ ㅠㅠㅠ
저도 지쳤어요 땡벌땡벌 🐝🐝🐝

2021-09-18 15:59 UTC, ddongule commented on src/css/global.css
> +
사랑해요 . 🧡

2021-09-22 10:22 UTC, HyuuunjuKim commented
ㅎㅎㅎ 그루밍 마크업 미션 너무 수고하셨습니다 👍🏻 즐거운 추석 보내구 담주에 만나욧 💛

2021-09-22 10:23 UTC, merged