Zigsong
woowacourse/html-apple-store pull request #8
Opened 2021-09-16 00:00 UTC by zigsong

## [🍎 데모 페이지](https://zigsong.github.io/html-apple-store/)

## 📝 PR 올리기 전 체크해봤나요?
- [x] 불필요한 마크업은 없는가?
- [x] 웹표준에 어긋나는 마크업은 없는가?
- [ ] css를 없앴을 때 실제 apple 웹사이트와 구조가 동일한가?
- [x] 모바일 화면에 맞게 반응형을 지원하는가?

## ✅ 마크업을 잘하기 위한 셀프 체크리스트
### 1. **시맨틱**
- [ ]  문서의 구조가 이해되기 쉽게 작성되었는가?
- [ ]  특정 태그 사용 전에 MDN을 확인했는가?
- [ ]  div 남발금지: div 가 있다면 대체할만한 태그는 없는가?

### 2. **레이아웃**
- [ ]  레이아웃 박스 구조는 적절하게 짜여있는가?
- [ ]  CSS를 없앴을 때 실제 apple 웹사이트와 구조가 동일한가?

### 3. **반응형**
- [ ]  반응형에 대응한 CSS를 작성했는가?
- [ ]  반응형이 고려되었는가?
- [ ]  필요 시, 모바일 우선으로 작성했는가?

### 4. **웹표준 / 접근성**
- [ ]  웹표준에 어긋나는 마크업은 없는가?
- [ ]  접근성 관련 속성을 잘 활용했는가?
- [ ]  스크린 리더로 읽어도 불편함이 없는가?

### 5. **중복 x / 불필요 x**
- [ ]  불필요하거나 반복적인 요소는 없는가?
- [ ]  중복이 있는 스타일을 잘 추출했는가?

## 😮 새로 알게된 것
- `background-position`을 잘 활용해봐야겠다.
- html css를 배운 초반에만 `float` 속성을 활용했었는데, 생각보다 유용하게 사용할 수 있을 것 같다.
- 애플은 각 섹션의 이미지를 `<img />`가 아닌 `background` 속성으로 주었는데, 뷰포트(디바이스)에 따라 `device-pixel-ratio`, `min-resolution` 등의 breakpoint를 줄 수 있다는 점이 신기하고 ~변태같기도 하고~ 
- 섹션 이미지 위치 조정을 위해 `transform: matrix` 속성을 줄 수 있다. (계산은 어려워서 사실 애플 공홈에서 갖다 썼다.)
- `<a href="" />` 태그 안에는 목적을 알 수 있는 적절한 이름(텍스트)가 들어가야 한다.
- `font-weight`는 hover 시 transition이 먹히지 않으므로 `text-shadow` 옵션을 줄 수 있다. 

## 🤔 고민 & 궁금 &느낀 점  
- 애플은 사진 애니메이션 때문인지 `will-change` 속성을 곳곳에 사용하는데, 구체적으로 GPU 단에서 어떻게 처리되는 건지 궁금하다.
- 정확히 언제 `margin`을 쓰고, 언제 `padding`을 쓰는 걸까? 
- scss 없이 그냥 css 선택자로만 하는 건 정말 귀찮고 어렵다.
- 그냥 디자인 때문이라도 (일부러 잘 안 보이게 하려고?) 폰트 색상과 배경색의 대비를 낮게 줘도 되는 걸까? 색상 대비가 낮은데 애플 공홈은 어떻게 lighthouse Accessibility 점수가 97일까? (색상 그대로 갖다 쓰니까 나는 그 문제 때문에 처음에는 80점 나왔는데!)

2021-09-16 01:19 UTC, GwangYeol-Im requested changes
같은 미션을 진행한 입장에서 봐도 기간 안에 이 정도로 마크업을 진행하는 것이 정말 쉽지 않았을 텐데 고생 많으셨어요 ㅎㅎ 고민과 질문에 대해서 그냥 제 생각만 짧게 공유하고 리뷰 마치도록 할게요~!

> 정확히 언제 margin을 쓰고, 언제 padding을 쓰는 걸까?

저는 디자인 시안을 해치지 않고 간격만 정확하다면 뭘 써도 상관없다는 주의입니다. 다만 padding만을 사용해야할 때는 주로 적용된 간격에 박스 내의 스타일을 같이 적용하고 싶을 때, 그 반대일 경우 margin으로 나눠볼 수는 있겠네요!

2021-09-16 01:19 UTC, igy95 commented on index.html
> +  <link href="./src/index.css" rel="stylesheet" type="text/css" />
`type="text/css"`를 넣었을 때 어떤 차이가 있나요?? 궁금해서 질문 남겨요 😊

2021-09-16 01:19 UTC, igy95 commented on src/global.css
> +:root {
`global.css`와 `common.css`는 어떤 기준으로 나누게 된 걸까요? 한 눈에 봤을 때는 뭔가 비슷해 보여 질문 남겨요!

2021-09-16 01:19 UTC, igy95 commented on src/footer.css
> +@media screen and (max-width: 767px) {
미디어 쿼리에서 구문이나 break point도 `root`로 관리하면 더 좋지 않을까 싶어요! 이러한 부분은 기획 단에서 자주 바뀔 수 있는 영역인 것 같은데 한 곳에서 관리하는 게 유지보수 측면에서 편할 듯 하네요 ㅎㅎ 지그 생각은 어떠신가요?

2021-09-16 01:19 UTC, igy95 commented on index.html
> +    <nav class="gnb">
저도 주로 header와 nav를 번갈아쓰거나 중첩해서 쓰고는 하는데 이 두 태그를 사용하는 본인만의 기준이 있을까요??

2021-09-16 01:19 UTC, igy95 commented on index.html
> +          <div class="cta-links">
저는 `gnb`, `cta` 같은 약어같은 경우, 개발자 도구를 열어서 사이트와 일일이 비교하지 않는 한 어떤 의미인지 이해하기 어렵더라구요 ㅠ 개발자 입장에서는 타이핑을 줄이는 게 더 효율적이지만, 가독성을 생각해 본다면 길더라도 풀어서 써주는 게 좋지 않을까하는 입장이에요! 다만 팀 내에서 컨벤션이 잡혀있는 상황이라면 괜찮을 수도 있고 이러한 부분은 스타일 차이라고 생각하기 때문에 고려만 해보고 선택적으로 수용해주면 좋을 것 같습니다 😊 (다시 고칠 필요는 없다는 얘기입니다!)

2021-09-16 01:19 UTC, GwangYeol-Im commented on index.html
> +  <footer>
이 푸터를 누가 채울까 했는데, 여기 있었군요... 리스펙합니다👍🏻

2021-09-16 14:47 UTC, zigsong commented on index.html
> +  <link href="./src/index.css" rel="stylesheet" type="text/css" />
오호 그냥 습관적으로 적어준 거였는데 카일 말 듣고 찾아봤네요! 
`link`가 어떤 타입인지 명시적으로 알려주는 역할인데, HTML5부터는 기재하지 않아도 상관없다고 합니다 ㅎㅎ

2021-09-16 14:48 UTC, zigsong commented on src/global.css
> +:root {
`global`은 css variables를 위한 목적인데 `common` 안에도 이것저것 있으니 같이 넣어도 되겠네요!! ㅎㅎ

2021-09-16 14:58 UTC, zigsong commented on src/footer.css
> +@media screen and (max-width: 767px) {
좋은 의견이라고 생각합니다! 
다만 break point들이 현재 딱히 여러번 재사용되는 부분들이 없어서 변수화해주지 않았어요 ㅎㅅㅎ

2021-09-16 15:00 UTC, zigsong commented on index.html
> +          <div class="cta-links">
저는 `gnb`, `cta` 모두 널리 사용되는 표현이라고 생각해서 썼는데, 그렇게 생각할 수도 있겠군요!! 
아니면 `cta-xxx`와 같이 postfix를 붙여줘도 되겠네요 ㅎㅎ
좋은 의견 감사합니당 😊

2021-09-16 15:10 UTC, zigsong commented on index.html
> +    <nav class="gnb">
기준이라기보다는 header 안에 nav가 포함되는 게 자연스럽다고 생각했는데, 찾아보니 이 방식을 선호하지 않는 사람들도 있는 것 같군요! 
이렇게 써도 되고, 분리해도 될 것 같습니다 ㅎㅎ

2021-09-17 02:32 UTC, zigsong commented
@GwangYeol-Im 
global 파일은 삭제하고, css variables는 common에 넣어주었습니다! 좋은 의견 감사드려요 😆
모바일에서 일부 깨지는 부분들 발견하여 같이 수정해서 올립니다 ㅎㅎ

2021-09-17 02:35 UTC, GwangYeol-Im approved these changes
이 와중에 모바일도 수정하다니.. ㄷㄷ 확인 마쳤습니다 :) 짧은 시간 동안 미션하느라 고생많았어요! approve 남기도록 할게요~

2021-09-22 10:03 UTC, merged